# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

source 'https://github.com/dicodingacademy/Modularization-CorePodSpecs-Module'

use_frameworks!
workspace 'Modularization'

target 'App' do
  # Pods for App
end

target 'Common' do
  project '../Common/Common'
end

target 'Cart' do
  project '../Cart/Cart'
  pod 'Core'
end

target 'Product' do
  project '../Product/Product'
  pod 'Core'
end