# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

use_frameworks!

workspace 'Modularization'

target 'App' do
# Pods for App

end

target 'Common' do
project '../Common/Common'

end